version: '3.1'
services:
 Mysql:
   image: mysql:8.0.16
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: admin
   ports:
     - 3306:3306
   container_name: mysql8

 MsSql:
   image:  microsoft/mssql-server-linux:2017-latest
   environment:
     MSSQL_SA_PASSWORD: mudar@123
     ACCEPT_EULA: "Y"
   ports:
     - 11433:1433
   container_name: mssql
